---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

“Beware the Jabberwock, my son! 
    
      The jaws that bite, the claws that catch! 

Beware the Jubjub bird, and shun 
      
      The frumious Bandersnatch!”

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->



Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth; 

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea, 
   
   Shining with all his might:

He did his very best to make 
   
   The billows smooth and bright
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
“Will you walk a little faster?”

said a whiting to a snail.

“There’s a porpoise close behind us,

and he’s treading on my tail.

See how eagerly the lobsters and

the turtles all advance!

They are waiting on the shingle—

will you come and join the dance?